apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skipa-prometheus-data
  namespace: skala3-finalproj-class2-team8
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
