apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team8-skipa
  namespace: skala-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/skipers/skipa-infra.git
    targetRevision: main
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: skala-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true