apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yml
- deployment.yml
- service.yml
- ingress.yml

images:
- name: amdp-registry.skala-ai.com/skala26a-ai2/skipa-backend
  newName: amdp-registry.skala-ai.com/skala26a-ai2/skipa-backend
  newTag: dev-1edec9a
