apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml
- ingress.yml

images:
- name: amdp-registry.skala-ai.com/skala26a-ai2/skipa-frontend
  newName: amdp-registry.skala-ai.com/skala26a-ai2/skipa-frontend
  newTag: dev-cf9e83e
