apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

images:
  - name: amdp-registry.skala-ai.com/skala3-finalproj-class2-team8/skipa-frontend
    newTag: dev-latest