apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- report-worker-deployment.yml
- patent-extract-worker-deployment.yml
- pre-evaluation-worker-deployment.yml
- service.yml
- ingress.yml
- configmap.yml
- ai-mode-openai-configmap.yml
- ai-mode-opensource-configmap.yml

images:
- name: amdp-registry.skala-ai.com/skala26a-ai2/skipa-ai
  newName: amdp-registry.skala-ai.com/skala26a-ai2/skipa-ai
  newTag: dev-72c66dd
